"""Render canonical contracts to registry YAML and sample flat fragments."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Literal

import yaml

from .flatten import flatten_canonical
from .schema import CanonicalContract

EmitMode = Literal["sample", "registry", "both"]

EVOLVE_LATER_COMMENTS = """\
# evolve-later: Post-Execution Monitor aggregate thresholds (DIR Governance section 2)
# aggregate_thresholds:
#   max_average_discount_30d: 0.10
#   max_rejection_rate_7d: 0.25

# evolve-later: JIT drift envelope for Topology B / SDS (DIR Topologies)
# drift_envelope:
#   max_price_slippage_pct: 0.5
#   max_context_age_seconds: 30

# evolve-later: expand authorized instruments after observation window
# authorized_instruments:
#   - ADDITIONAL-SCOPE-1

# evolve-later: semantic business rules (evolve via Contract Evolution Loop)
# semantic_rules:
#   - rule_id: example_rule
#     description: "Add after telemetry review"
"""


def render_registry_yaml(contract: CanonicalContract) -> str:
    """Render standalone nested YAML for Agent Registry / CI/CD."""
    header = (
        "# agent_contract.yaml — registered via CI/CD pipeline, NOT self-registered by agent\n"
        f"# Bootstrap v{contract.version} — generated by tools/contract\n"
    )
    body = yaml.dump(
        contract.model_dump(exclude_none=True),
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )
    return header + body + "\n" + EVOLVE_LATER_COMMENTS


def render_sample_fragment(contract: CanonicalContract) -> str:
    """Render flat contract block for samples/*/config.yaml."""
    flat = flatten_canonical(contract)
    flat.pop("agent_id", None)

    # Include governance metadata useful for samples
    sample_block: Dict[str, Any] = {
        "version": contract.version,
        "owner": contract.owner,
        **flat,
    }

    header = (
        "# contract fragment — paste under `contract:` or `agents[].contract` in config.yaml\n"
        f"# Bootstrap v{contract.version} — generated by tools/contract\n"
    )
    body = yaml.dump(
        sample_block,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )
    return header + body + "\n" + EVOLVE_LATER_COMMENTS


def write_emitted_files(
    contract: CanonicalContract,
    emit: EmitMode,
    out_dir: Path,
) -> Dict[str, Path]:
    """Write registry and/or sample files; return paths written."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: Dict[str, Path] = {}

    safe_id = contract.agent_id.replace("/", "_").replace(" ", "_")
    version = contract.version

    if emit in ("registry", "both"):
        registry_path = out_dir / f"{safe_id}.v{version}.yaml"
        registry_path.write_text(render_registry_yaml(contract), encoding="utf-8")
        written["registry"] = registry_path

    if emit in ("sample", "both"):
        sample_path = out_dir / f"{safe_id}.sample-contract.yaml"
        sample_path.write_text(render_sample_fragment(contract), encoding="utf-8")
        written["sample"] = sample_path

    return written
