-- =============================================================================
-- Sample 08 — PostgreSQL DDL for the full DIR repository (canonical model)
-- =============================================================================
--
-- This file is the PostgreSQL equivalent of the authoritative SQLite DDL in:
--   src/dir_core/storage/schema.sql
--
-- Same logical tables and semantics; types mapped for PostgreSQL (JSONB,
-- TIMESTAMPTZ, DOUBLE PRECISION, GENERATED IDENTITY for surrogate keys).
--
-- HOW TO APPLY
--   psql -U dir_user -d dir_quickstart -f schema.sql
--
-- Or from Python (see dir_repo.apply_schema in this sample).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- DIR §2.3 — Agent Registry
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_registry (
    agent_id          TEXT        PRIMARY KEY,
    contract          JSONB       NOT NULL DEFAULT '{}',
    priority          INTEGER     NOT NULL DEFAULT 0,
    status            TEXT        NOT NULL DEFAULT 'ACTIVE',
    agent_version     TEXT,
    session_token     TEXT,
    suspension_reason TEXT,
    registered_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- DIR §8 — Context Store: per-flow session (dfid-scoped)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS context_session (
    dfid       TEXT        PRIMARY KEY,
    data       JSONB       NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- DIR §8 — Context Store: persistent agent state
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS context_state (
    agent_id   TEXT        PRIMARY KEY,
    data       JSONB       NOT NULL DEFAULT '{}',
    version    INTEGER     NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- DIR §7 — Idempotency cache
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS idempotency_cache (
    key        TEXT        PRIMARY KEY,
    result     JSONB       NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- DIR §7 — Saga dirty-state log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saga_dirty_state (
    dfid               TEXT        PRIMARY KEY,
    failed_step        TEXT        NOT NULL DEFAULT '',
    partial_state_json JSONB       NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- DIR §6.2 — Resource locks
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resource_locks (
    dfid        TEXT        NOT NULL,
    resource_id TEXT        NOT NULL,
    amount      DOUBLE PRECISION NOT NULL DEFAULT 0,
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (dfid, resource_id)
);

-- -----------------------------------------------------------------------------
-- DIR §6.2 — Intent retry governor
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS intent_retry (
    dfid            TEXT        PRIMARY KEY,
    rejection_count INTEGER     NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- DIR §9 — Escalation budget (append-only token log)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS escalation_budget (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id   TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- DIR §9 — Escalation requests
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS escalation_requests (
    dfid           TEXT        PRIMARY KEY,
    agent_id       TEXT        NOT NULL,
    reason         TEXT        NOT NULL DEFAULT '',
    context_json   TEXT        NOT NULL DEFAULT '{}',
    proposal_json  TEXT        NOT NULL DEFAULT '{}',
    impact         TEXT        NOT NULL DEFAULT '',
    status         TEXT        NOT NULL DEFAULT 'PENDING',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at    TIMESTAMPTZ,
    human_decision TEXT
);

-- -----------------------------------------------------------------------------
-- DIR §4.3 — Lifecycle transition log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS flow_transitions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dfid        TEXT        NOT NULL,
    from_status TEXT,
    to_status   TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
