-- =============================================================================
-- PostgreSQL DDL — DIR Repository (canonical model)
-- Decision Intelligence Runtime (DIR)
-- =============================================================================
--
-- PostgreSQL equivalent of: src/dir_core/storage/schema.sql
--
-- Type mapping:
--   JSON      -> JSONB
--   TIMESTAMP -> TIMESTAMPTZ (DEFAULT NOW())
--   REAL      -> DOUBLE PRECISION
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--
-- HOW TO APPLY
--   psql -U dir_user -d dir_quickstart -f pg_schema.sql
--   Or: apply_schema(conn) in samples/shared/storage/pg_repo.py
-- =============================================================================

-- -----------------------------------------------------------------------------
-- DIR §2.3 — Agent Registry
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_registry (
    agent_id          TEXT        PRIMARY KEY,
    contract          JSONB       NOT NULL DEFAULT '{}',
    priority          INTEGER     NOT NULL DEFAULT 0,
    status            TEXT        NOT NULL DEFAULT 'ACTIVE',
    agent_version     TEXT,
    session_token     TEXT,
    suspension_reason TEXT,
    registered_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_registry_status
    ON agent_registry(status);

-- -----------------------------------------------------------------------------
-- DIR §4.3 — Decision Flows (Lifecycle root)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS decision_flows (
    dfid            TEXT        PRIMARY KEY,
    root_dfid       TEXT        NOT NULL,
    dfid_parent     TEXT,
    agent_id        TEXT        NOT NULL,

    flow_type       TEXT        NOT NULL DEFAULT 'DEFAULT',
    flow_version    TEXT        NOT NULL DEFAULT '1.0',

    status          TEXT        NOT NULL DEFAULT 'CREATED',

    created_by_type TEXT,
    created_by_id   TEXT,

    priority        INTEGER     NOT NULL DEFAULT 0,

    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (dfid_parent)
        REFERENCES decision_flows(dfid),

    FOREIGN KEY (agent_id)
        REFERENCES agent_registry(agent_id),

    CHECK (
        status IN (
            'CREATED',
            'RUNNING',
            'WAITING_ESCALATION',
            'COMPLETED',
            'FAILED',
            'CANCELLED',
            'COMPENSATING',
            'COMPENSATED'
        )
    ),
    CHECK (
        (dfid_parent IS NULL AND root_dfid = dfid) OR
        (dfid_parent IS NOT NULL AND root_dfid != '')
    )
);

CREATE INDEX IF NOT EXISTS idx_decision_flows_root_dfid
    ON decision_flows(root_dfid);
CREATE INDEX IF NOT EXISTS idx_decision_flows_parent
    ON decision_flows(dfid_parent);
CREATE INDEX IF NOT EXISTS idx_decision_flows_agent_id
    ON decision_flows(agent_id);
CREATE INDEX IF NOT EXISTS idx_decision_flows_status
    ON decision_flows(status);
CREATE INDEX IF NOT EXISTS idx_decision_flows_created_at
    ON decision_flows(created_at);

-- -----------------------------------------------------------------------------
-- DIR §8 — Context Store: per-flow session data
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS flow_context (
    dfid        TEXT        PRIMARY KEY,
    data        JSONB       NOT NULL DEFAULT '{}',
    version     INTEGER     NOT NULL DEFAULT 1,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (dfid)
        REFERENCES decision_flows(dfid)
        ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- DIR §8 — Context Store: persistent agent state
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_state (
    agent_id    TEXT        PRIMARY KEY,
    data        JSONB       NOT NULL DEFAULT '{}',
    version     INTEGER     NOT NULL DEFAULT 1,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (agent_id)
        REFERENCES agent_registry(agent_id)
        ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- DIR §8 — Context Store: decision feedback (Epistemic Trajectory)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS decision_feedback_trajectory (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    TEXT        NOT NULL,
    dfid        TEXT        NOT NULL,
    status      TEXT        NOT NULL,
    reason      TEXT,
    score       DOUBLE PRECISION,
    source      TEXT        NOT NULL DEFAULT 'KERNEL',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (agent_id) REFERENCES agent_registry(agent_id) ON DELETE CASCADE,
    FOREIGN KEY (dfid) REFERENCES decision_flows(dfid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_decision_feedback_agent
    ON decision_feedback_trajectory(agent_id);

-- -----------------------------------------------------------------------------
-- DIR §7 — Idempotency Cache
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS idempotency_cache (
    idempotency_key TEXT        PRIMARY KEY,
    request_hash    TEXT        NOT NULL,
    result          JSONB       NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_idempotency_cache_expires_at
    ON idempotency_cache(expires_at);

-- -----------------------------------------------------------------------------
-- DIR §7 — Saga / Compensation: dirty-state log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saga_dirty_state (
    dfid               TEXT        PRIMARY KEY,
    failed_step        TEXT        NOT NULL DEFAULT '',
    partial_state_json JSONB       NOT NULL DEFAULT '{}',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (dfid)
        REFERENCES decision_flows(dfid)
        ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- DIR §6.2 — Resource Lock Manager
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resource_locks (
    resource_id   TEXT        PRIMARY KEY,
    dfid          TEXT        NOT NULL,
    amount        DOUBLE PRECISION NOT NULL DEFAULT 0,
    acquired_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at    TIMESTAMPTZ,

    FOREIGN KEY (dfid)
        REFERENCES decision_flows(dfid)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_resource_locks_dfid
    ON resource_locks(dfid);
CREATE INDEX IF NOT EXISTS idx_resource_locks_expires_at
    ON resource_locks(expires_at);

-- -----------------------------------------------------------------------------
-- DIR §6.2 — Intent Retry Governor
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS intent_retry (
    dfid               TEXT        PRIMARY KEY,
    rejection_count    INTEGER     NOT NULL DEFAULT 0,
    max_retries        INTEGER     NOT NULL DEFAULT 3,
    retry_policy       TEXT        NOT NULL DEFAULT 'EXPONENTIAL_BACKOFF',
    next_retry_at      TIMESTAMPTZ,
    backoff_until      TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (dfid)
        REFERENCES decision_flows(dfid)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_intent_retry_next_retry_at
    ON intent_retry(next_retry_at);

-- -----------------------------------------------------------------------------
-- DIR §9 — Escalation Manager: rate-limit budget
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS escalation_budget (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id     TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (agent_id)
        REFERENCES agent_registry(agent_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_escalation_budget_agent_id
    ON escalation_budget(agent_id);
CREATE INDEX IF NOT EXISTS idx_escalation_budget_created_at
    ON escalation_budget(created_at);

-- -----------------------------------------------------------------------------
-- DIR §9 — Escalation Manager: pending and resolved requests
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS escalation_requests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dfid             TEXT        NOT NULL,
    root_dfid        TEXT        NOT NULL,
    agent_id         TEXT        NOT NULL,

    reason           TEXT        NOT NULL DEFAULT '',
    context_json     JSONB       NOT NULL DEFAULT '{}',
    proposal_json    JSONB       NOT NULL DEFAULT '{}',
    impact           TEXT        NOT NULL DEFAULT '',
    status           TEXT        NOT NULL DEFAULT 'PENDING',
    human_decision   TEXT,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at      TIMESTAMPTZ,

    FOREIGN KEY (dfid) REFERENCES decision_flows(dfid) ON DELETE CASCADE,
    FOREIGN KEY (agent_id) REFERENCES agent_registry(agent_id),

    CHECK (
        status IN (
            'PENDING',
            'APPROVED',
            'REJECTED',
            'CANCELLED'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_escalation_requests_dfid
    ON escalation_requests(dfid);
CREATE INDEX IF NOT EXISTS idx_escalation_requests_root_dfid
    ON escalation_requests(root_dfid);
CREATE INDEX IF NOT EXISTS idx_escalation_requests_agent_id
    ON escalation_requests(agent_id);
CREATE INDEX IF NOT EXISTS idx_escalation_requests_status
    ON escalation_requests(status);

-- -----------------------------------------------------------------------------
-- DIR §4.3 — Lifecycle: flow transition log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS flow_transitions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dfid           TEXT        NOT NULL,
    root_dfid      TEXT        NOT NULL,
    from_status    TEXT,
    to_status      TEXT        NOT NULL,
    correlation_id TEXT,
    causation_id   TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (dfid) REFERENCES decision_flows(dfid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_flow_transitions_dfid
    ON flow_transitions(dfid);
CREATE INDEX IF NOT EXISTS idx_flow_transitions_root_dfid
    ON flow_transitions(root_dfid);
CREATE INDEX IF NOT EXISTS idx_flow_transitions_created_at
    ON flow_transitions(created_at);

-- -----------------------------------------------------------------------------
-- Observability — append-only decision audit events
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS decision_audit_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dfid            TEXT        NOT NULL,
    root_dfid       TEXT        NOT NULL,

    event_type      TEXT        NOT NULL,
    severity        TEXT        NOT NULL DEFAULT 'INFO',
    correlation_id  TEXT,
    causation_id    TEXT,

    step_id         TEXT        NOT NULL DEFAULT '',
    state           TEXT        NOT NULL DEFAULT '',

    detail_json     JSONB       NOT NULL DEFAULT '{}',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    FOREIGN KEY (dfid) REFERENCES decision_flows(dfid) ON DELETE CASCADE,

    CHECK (
        severity IN (
            'DEBUG',
            'INFO',
            'WARNING',
            'ERROR',
            'CRITICAL'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_decision_audit_events_dfid
    ON decision_audit_events(dfid);
CREATE INDEX IF NOT EXISTS idx_decision_audit_events_root_dfid
    ON decision_audit_events(root_dfid);
CREATE INDEX IF NOT EXISTS idx_decision_audit_events_event_type
    ON decision_audit_events(event_type);
CREATE INDEX IF NOT EXISTS idx_decision_audit_events_created_at
    ON decision_audit_events(created_at);
CREATE INDEX IF NOT EXISTS idx_decision_audit_events_severity
    ON decision_audit_events(severity);
